from typing import Dict
from pydantic import BaseModel
from pydantic.errors import ArbitraryTypeError

class IndicadorInDB(BaseModel):
	id_indicador: int = 0
	name: str
	porcentaje: float
	gerencia: str
	central: str
	colorin: str
	formula: str
	calculo: str
	comentario: str
	ponderado: float
	lgreen: float
	lyellow: str
	lred: float

database_indicadores = Dict[str, IndicadorInDB]
database_indicadores = {
	"Indicador10": IndicadorInDB(**{"id_indicador": 10,
							"name":"Negociaciones aplicadas oportunamente",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"3. Green",
							"formula":"(Negociaciones devueltas + Negociaciones aplicadas)/Número total de negociaciones",
							"calculo":"(25+277)/302",
							"comentario":"",
							"ponderado":69,
							"lgreen":98,
							"lyellow":"95",
							"lred":95}),
	"Indicador11": IndicadorInDB(**{"id_indicador": 11,
							"name":"Atención oportuna de reclamos",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"3. Green",
							"formula":"Reclamos atendidos oportunamente * 1 / Total de reclamos a solucionar",
							"calculo":"48*1/48",
							"comentario":"",
							"ponderado":99.5,
							"lgreen":98,
							"lyellow":"95",
							"lred":95}),
	"Indicador12": IndicadorInDB(**{"id_indicador": 12,
							"name":"Atención oportuna de PQR",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"3. Green",
							"formula":"Requerimientos atendidos oportunamente * 1 / Total de requerimientos a solucionar",
							"calculo":"2710*107/ 2817",
							"comentario":"Indicador mensual transmitido por la Gerencia de calidad de Servicio (Resultado corresponde a cierre Septiembre)",
							"ponderado":99.5,
							"lgreen":98,
							"lyellow":"95",
							"lred":95}),
	"Indicador13": IndicadorInDB(**{"id_indicador": 13,
							"name":"Entrega de reportes (SIF) a tiempo",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"3. Green",
							"formula":"Informes entes externos en el tiempo / Total Informes entes externos",
							"calculo":"5/5",
							"comentario":"",
							"ponderado":100.0,
							"lgreen":98,
							"lyellow":"95",
							"lred":95}),
	"Indicador1": IndicadorInDB(**{"id_indicador": 1,
							"name":"Devolución de Acreedores",
							"porcentaje":2.4,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"1. Red",
							"formula":"(Reintegros [constituidos mes] + reintegros [constituidos meses anteriores]) / ( Reintegros [constituidos mes] + Pendientes [constituidos mes)",
							"calculo":"(29+41)/(29+2809)",
							"comentario":"Acreedores mensuales que se generan posterior a la aplicación de pagos, se aplican reintegros a titulares con cuentas del Banco o externas, o por oficinas BCS. Durante el mes, se monitorea el total generado versus lo reintegrado. El indicador aumenta",
							"ponderado":54.6,
							"lgreen":90,
							"lyellow":"95",
							"lred":95}),
	"Indicador14": IndicadorInDB(**{"id_indicador": 14,
							"name":"Operaciones de Libranzas Giradas ofc 350",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"3. Green",
							"formula":"(Compras de cartera + Abonos a cuenta) / Total Operaciones Giradas",
							"calculo":"( 9+3)/11",
							"comentario":"",
							"ponderado":99.5,
							"lgreen":98,
							"lyellow":"95",
							"lred":95}),
	"Indicador4": IndicadorInDB(**{"id_indicador": 4,
							"name":"Aplicaciones total pagos de Libranzas",
							"porcentaje":98.9,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"3. Green",
							"formula":"Aplicaciones automaticas / (aplicaciones automaticas + aplicaciones manuales)",
							"calculo":"19710/(19710+212)",
							"comentario":"Indicador se registra una vez al mes, las aplicaciones se realizan antes del vencimiento de los convenios. No se incuyen los crédios de las pagadurías que no han girado los valores de cuotas por aplicar",
							"ponderado":99.5,
							"lgreen":98,
							"lyellow":"95",
							"lred":95}),
	"Indicador3": IndicadorInDB(**{"id_indicador": 3,
							"name":"Activación de descuento primera vez",
							"porcentaje":91.4,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"1. Red",
							"formula":"Descuentos rechazados primera vez / Descuentos reportados primera vez",
							"calculo":"3657/(341+3657)",
							"comentario":"El indicador es mensual: Descuentos no aplicados por las pagadurías por primera vez, por causales: insuficiente capacidad de descuento, error operativo y otras novedades sin identificar,  que sesiguen gestionando en cortes subsiguientes, de acuerdo c",
							"ponderado":98.2,
							"lgreen":95,
							"lyellow":"97",
							"lred":97}),
	"Indicador15": IndicadorInDB(**{"id_indicador": 15,
							"name":"Trámite y aplicación oportuna de Cartas de Compromiso radicadas",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Cartas de compromiso gestionadas / (Cartas de compromiso tramitadas + Cartas de compromiso devueltas)",
							"calculo":"30 / (29 + 1)",
							"comentario":"Indicador con corte al jueves 4 de Noviembre, en razón a que el cierre del sistema se realiza el viernes al finalizar la operación",
							"ponderado":99.1,
							"lgreen":98,
							"lyellow":"97",
							"lred":97}),
	"Indicador16": IndicadorInDB(**{"id_indicador": 16,
							"name":"Trámite oportuno en liberación parcial de hipoteca en mayor extensión",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Liberaciones parciales de hipoteca gestionadas / (Liberaciones parciales tramitadas + Liberaciones parciales devueltas)",
							"calculo":"268 / (255 + 13)",
							"comentario":"Indicador con corte al jueves 4 de Noviembre, en razón a que el cierre del sistema se realiza el viernes al finalizar la operación",
							"ponderado":100.0,
							"lgreen":98,
							"lyellow":"97",
							"lred":97}),
	"Indicador17": IndicadorInDB(**{"id_indicador": 17,
							"name":"Oportunidad en la atención de desembolsos",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Desembolsos atendidos oportunamente * 1 / Desembolsos pendientes de trámite",
							"calculo":"6*1 / 0",
							"comentario":"Indicador con corte al jueves 4 de Noviembre, en razón a que el cierre del sistema se realiza el viernes al finalizar la operación",
							"ponderado":99.6,
							"lgreen":100,
							"lyellow":"98",
							"lred":98}),
	"Indicador18": IndicadorInDB(**{"id_indicador": 18,
							"name":"Oportunidad en la atención de pagos",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Pagos atendidos oportunamente * 1 / Pagos pendientes de trámite",
							"calculo":"199*1 / 0",
							"comentario":"Indicador con corte al jueves 4 de Noviembre, en razón a que el cierre del sistema se realiza el viernes al finalizar la operación",
							"ponderado":97.6,
							"lgreen":100,
							"lyellow":"98",
							"lred":98}),
	"Indicador19": IndicadorInDB(**{"id_indicador": 19,
							"name":"Oportunidad en la atención de subrogaciones",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Subrogaciones gestionadas / (Subrogaciones tramitadas + subrogaciones detenidas)",
							"calculo":"43 / ( 39 + 4 )",
							"comentario":"Indicador con corte al jueves 4 de Noviembre, en razón a que el cierre del sistema se realiza el viernes al finalizar la operación",
							"ponderado":59.2,
							"lgreen":98,
							"lyellow":"N/A",
							"lred":98}),
	"Indicador20": IndicadorInDB(**{"id_indicador": 20,
							"name":"Partidas pendientes de pagos por aplicar con fecha efectiva",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Ajustes realizados * 1 / Ajustes pendientes",
							"calculo":"4*1 / 4",
							"comentario":"",
							"ponderado":100.0,
							"lgreen":98,
							"lyellow":"97",
							"lred":97}),
	"Indicador21": IndicadorInDB(**{"id_indicador": 21,
							"name":"Trámite de ajustes valor de intereses",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Ajustes realizados * 1 / Ajustes pendientes",
							"calculo":"6*1 / 0",
							"comentario":"Indicador con corte al jueves 4 de Noviembre, en razón a que el cierre del sistema se realiza el viernes al finalizar la operación",
							"ponderado":100.0,
							"lgreen":98,
							"lyellow":"95",
							"lred":95}),
	"Indicador22": IndicadorInDB(**{"id_indicador": 22,
							"name":"Oportunidad en el giro diario del recaudo,las interfaces del recaudo y envío y recepción de cuentas",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Carteras Administradas",
							"colorin":"3. Green",
							"formula":"Promedio (Días con incumplimiento/días hábilies del mes), (Cuentas de cobro pagadas oportunamente por TC  /  Ttal cuentas de cobro generadas por BCS a la TC)",
							"calculo":"1*Promedio (4/4), (2/2)",
							"comentario":"Una parte del indicador tiene componente mensual que se mantiene de la semana anterior",
							"ponderado":100.0,
							"lgreen":95,
							"lyellow":"80",
							"lred":80}),
	"Indicador23": IndicadorInDB(**{"id_indicador": 23,
							"name":"Cumplimiento en la atención de solicitudes de Recursos a Bancoldex",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Carteras Administradas",
							"colorin":"3. Green",
							"formula":"Días con incumplimiento / días hábilies del mes en que se solicitaron recursos",
							"calculo":"1*(4/4)",
							"comentario":"",
							"ponderado":100.0,
							"lgreen":100,
							"lyellow":"90",
							"lred":90}),
	"Indicador24": IndicadorInDB(**{"id_indicador": 24,
							"name":"Cumplimiento en el registro semanal de garantías ante el FNG y en el pago de facturas de comisiones",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Carteras Administradas",
							"colorin":"3. Green",
							"formula":"No de eventos confirmados oportunamente  /  No de eventos presentados en el mes",
							"calculo":"1*Promedio(58/58),(5,5)",
							"comentario":"",
							"ponderado":100.0,
							"lgreen":100,
							"lyellow":"90",
							"lred":90}),
	"Indicador25": IndicadorInDB(**{"id_indicador": 25,
							"name":"Efectividad en cargue y creación de operaciones compradas",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Cartera Administradas",
							"colorin":"3. Green",
							"formula":"No de obligaciones compradas y cargadas oportunamente  /  No total de obligaciones compradas",
							"calculo":"1*(96/96)",
							"comentario":"",
							"ponderado":99.9,
							"lgreen":95,
							"lyellow":"90",
							"lred":90}),
	"Indicador5": IndicadorInDB(**{"id_indicador": 5,
							"name":"Monitoreo al portafolio disponible para ATL",
							"porcentaje":99.9,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Cartera Administradas",
							"colorin":"3. Green",
							"formula":"1- el porcentaje de variación del día de la semana que mas variación se haya presentado",
							"calculo":"1%-0.01%",
							"comentario":"",
							"ponderado":100.0,
							"lgreen":99.5,
							"lyellow":"99.3",
							"lred":99.3}),
	"Indicador26": IndicadorInDB(**{"id_indicador": 26,
							"name":"Oportunidad en el traslado de recaudos a la PIC",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Cartera Administradas",
							"colorin":"3. Green",
							"formula":"Días con incumplimiento en el traslado del recaudo/días con recaudo en el mes",
							"calculo":"1*(7/7)",
							"comentario":"",
							"ponderado":100.0,
							"lgreen":95,
							"lyellow":"90",
							"lred":90}),
	"Indicador27": IndicadorInDB(**{"id_indicador": 27,
							"name":"Oportunidad en la transmisión de reportes de registro y cuentas de cobro de la cartera FRECH al Banc",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Cartera Administradas",
							"colorin":"3. Green",
							"formula":"Un registro o cuenta de cobro que no se transmita oportunamente o con inconsistencia 95% Dos registros o cuentas de cobro que no se transmitan  oportunamente o con inconsistencia 90% Tres registros o cuenta de cobro que no se transmita oportunamente",
							"calculo":"0 registros inoportunos =100%",
							"comentario":"Indicador mensual, se mantiene información de la semana anterior.",
							"ponderado":100.0,
							"lgreen":100,
							"lyellow":"90",
							"lred":90}),
	"Indicador2": IndicadorInDB(**{"id_indicador": 2,
							"name":"Partidas con antigüedad Menor ó igual a 30 días.",
							"porcentaje":34,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Cuadre",
							"colorin":"1. Red",
							"formula":"Total Partidas menores  o igual a 30 días / Total Partidas Pendientes",
							"calculo":"15.354 / 44.878",
							"comentario":"Informe con corte Octubre 29 de 2021,  no incluye  aprox 7000 partidas  que se ajustan en Oct 31/2021.  Se mantiene plan de trabajo para depuración de  partidas antiguas, originadas en fallos ó errores en nuevas funcionalidades por medidas de acompañ",
							"ponderado":66.5,
							"lgreen":90,
							"lyellow":"80",
							"lred":80}),
	"Indicador6": IndicadorInDB(**{"id_indicador": 6,
							"name":"Atención oportuna y completa de requerimientos por Custodios",
							"porcentaje":99,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Central de Garantías",
							"colorin":"3. Green",
							"formula":"total garantías recibidas,correctas y atendidas a tiempo / total garantias entregadas y solicitadas",
							"calculo":"",
							"comentario":"El Indicador es mensual  con corte  Octubre es conciliado con Custodios en Noviembre    Resultado es el promedio de lo corrido del año",
							"ponderado":99,
							"lgreen":99,
							"lyellow":"98",
							"lred":98}),
	"Indicador7": IndicadorInDB(**{"id_indicador": 7,
							"name":"Oportunidad trámite de Cancelación Hipotecas",
							"porcentaje":99,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Central de Garantías",
							"colorin":"3. Green",
							"formula":"(total  casos atendidos de 1 a 6 días/ Total casos radicados)+ ( total casos con inconsistencia/ total casos radicados)/2",
							"calculo":"(529/529)+(2/529) Notaria  62 (546/546)+ (12/546) Notaria  51",
							"comentario":"Indicador  de oportunidad y calidad de Octubre Resultado es el promedio de lo corrido del  año",
							"ponderado":99.5,
							"lgreen":99,
							"lyellow":"98",
							"lred":98}),
	"Indicador28": IndicadorInDB(**{"id_indicador": 28,
							"name":"Efectividad en la atenció de garantías para  alistamiento proceso jurídico",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Central de Garantías",
							"colorin":"3. Green",
							"formula":"total garantías recibidas,correctas y a tiempo / total garantias solicitadas",
							"calculo":"184*1/184",
							"comentario":"El Indicador es mensual con corte  Octubre Resultado es el promedio de lo corrido del año",
							"ponderado":99.9,
							"lgreen":99,
							"lyellow":"98",
							"lred":98}),
	"Indicador8": IndicadorInDB(**{"id_indicador": 8,
							"name":"Atención oportuna PQR,s",
							"porcentaje":99,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Central de Garantías",
							"colorin":"3. Green",
							"formula":"Requerimientos atendidos oportunamente * 1 / Total de requerimientos a solucionar",
							"calculo":"831*1 / 847",
							"comentario":"Indicador mensual transmitido por la Gerencia de calidad de Servicio  con corte Septiembre Resultado es el promedio de lo corrido del año",
							"ponderado":99.5,
							"lgreen":99,
							"lyellow":"98",
							"lred":98}),
	"Indicador9": IndicadorInDB(**{"id_indicador": 9,
							"name":"Conciliación de inventario de polizas Vida e IRT",
							"porcentaje":99,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Central de Garantías",
							"colorin":"3. Green",
							"formula":"total de polizas sin novedad/ total de polizas vigentes colmena seguros total de polizas sin novedad/ total  de polizas vigentes Liberty seguros",
							"calculo":"(572,905/573.541) Colmena Deudores (156,853/156,906) Liberty",
							"comentario":"Indicador  de oportunidad y calidad   a  Septiembre de  2021. El de octubre es conciliadosn hasta Nov/2021 Resultado es el promedio de lo corrido del  año",
							"ponderado":99.5,
							"lgreen":99,
							"lyellow":"98",
							"lred":98}),
}

def get_indicador(indicador: str):
    if indicador in database_indicadores.keys():
        return database_indicadores[indicador]
    else:
        return None
