from typing import Dict
from pydantic import BaseModel
from pydantic.errors import ArbitraryTypeError

class IndicadorInDB(BaseModel):
	id_indicador: int = 0
	name: str
	porcentaje: float
	gerencia: str
	central: str
	colorin: str
	formula: str
	calculo: str
	comentario: str
	ponderado: float
	lgreen: float
	lyellow: str
	lred: float

database_indicadores = Dict[str, IndicadorInDB]
database_indicadores = {
	"Indicador11": IndicadorInDB(**{"id_indicador": 11,
							"name":"Negociaciones aplicadas oportunamente",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"3. Green",
							"formula":"(Negociaciones devueltas + Negociaciones aplicadas)/Número total de negociaciones",
							"calculo":"(24+213)/237",
							"comentario":"Sin informacion",
							"ponderado":69,
							"lgreen":98,
							"lyellow":"95",
							"lred":95}),
	"Indicador12": IndicadorInDB(**{"id_indicador": 12,
							"name":"Atención oportuna de reclamos",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"3. Green",
							"formula":"Reclamos atendidos oportunamente * 1 / Total de reclamos a solucionar",
							"calculo":"63*1/63",
							"comentario":"Sin informacion",
							"ponderado":99.5,
							"lgreen":98,
							"lyellow":"95",
							"lred":95}),
	"Indicador3": IndicadorInDB(**{"id_indicador": 3,
							"name":"Atención oportuna de PQR",
							"porcentaje":99.7,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"3. Green",
							"formula":"Requerimientos atendidos oportunamente * 1 / Total de requerimientos a solucionar",
							"calculo":"2716*1/2722",
							"comentario":"Indicador mensual transmitido por la Gerencia de calidad de Servicio (Resultado corresponde a cierre Febrero)",
							"ponderado":99.3,
							"lgreen":98,
							"lyellow":"99",
							"lred":99}),
	"Indicador13": IndicadorInDB(**{"id_indicador": 13,
							"name":"Entrega de reportes (SIF) a tiempo",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"3. Green",
							"formula":"Informes entes externos en el tiempo / Total Informes entes externos",
							"calculo":"10/10",
							"comentario":"Sin informacion",
							"ponderado":100.0,
							"lgreen":98,
							"lyellow":"95",
							"lred":95}),
	"Indicador2": IndicadorInDB(**{"id_indicador": 2,
							"name":"Devolución de Acreedores",
							"porcentaje":89.0,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"1. Red",
							"formula":"(Reintegros [constituidos mes] + reintegros [constituidos meses anteriores]) / ( Reintegros [constituidos mes] + Pendientes [constituidos mes)",
							"calculo":"(4030+454)/(4030+1007)",
							"comentario":"Acreedores mensuales que se generan posterior a la aplicación de pagos, se aplican reintegros a los titulares con cuentas del Banco o externas, o a través de oficinas por excedente disponible durante el mes, se monitorea el total generado versus lo r",
							"ponderado":91.8,
							"lgreen":90,
							"lyellow":"95",
							"lred":95}),
	"Indicador14": IndicadorInDB(**{"id_indicador": 14,
							"name":"Operaciones de Libranzas Giradas ofc 350",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Operaciones e Información de Exóge",
							"colorin":"3. Green",
							"formula":"(Compras de cartera + Abonos a cuenta) / Total Operaciones Giradas",
							"calculo":"(99+28)/127",
							"comentario":"Sin informacion",
							"ponderado":99.5,
							"lgreen":98,
							"lyellow":"95",
							"lred":95}),
	"Indicador15": IndicadorInDB(**{"id_indicador": 15,
							"name":"Trámite y aplicación oportuna de Cartas de Compromiso radicadas",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Cartas de compromiso gestionadas / (Cartas de compromiso tramitadas + Cartas de compromiso devueltas)",
							"calculo":"84 / (82+2)",
							"comentario":"Indicadores con corte al jueves 24 de marzo, en razón a que el cierre del sistema se realiza el viernes al finalizar la operación, por lo tanto no es posible obtener informción al corte del viernes",
							"ponderado":100.0,
							"lgreen":98,
							"lyellow":"97",
							"lred":97}),
	"Indicador16": IndicadorInDB(**{"id_indicador": 16,
							"name":"Trámite oportuno en liberación parcial de hipoteca en mayor extensión",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Liberaciones parciales de hipoteca gestionadas / (Liberaciones parciales tramitadas + Liberaciones parciales devueltas)",
							"calculo":"138 / (126 + 12)",
							"comentario":"Indicadores con corte al jueves 24 de marzo, en razón a que el cierre del sistema se realiza el viernes al finalizar la operación, por lo tanto no es posible obtener informción al corte del viernes",
							"ponderado":100.0,
							"lgreen":98,
							"lyellow":"97",
							"lred":97}),
	"Indicador17": IndicadorInDB(**{"id_indicador": 17,
							"name":"Oportunidad en la atención de desembolsos",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Desembolsos atendidos oportunamente * 1 / Desembolsos pendientes de trámite",
							"calculo":"6*1 / 0",
							"comentario":"Indicadores con corte al jueves 24 de marzo, en razón a que el cierre del sistema se realiza el viernes al finalizar la operación, por lo tanto no es posible obtener informción al corte del viernes",
							"ponderado":99.1,
							"lgreen":100,
							"lyellow":"98",
							"lred":98}),
	"Indicador18": IndicadorInDB(**{"id_indicador": 18,
							"name":"Oportunidad en la atención de pagos",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Pagos atendidos oportunamente * 1 / Pagos pendientes de trámite",
							"calculo":"148*1 / 0",
							"comentario":"Indicadores con corte al jueves 24 de marzo, en razón a que el cierre del sistema se realiza el viernes al finalizar la operación, por lo tanto no es posible obtener informción al corte del viernes",
							"ponderado":100.0,
							"lgreen":100,
							"lyellow":"98",
							"lred":98}),
	"Indicador19": IndicadorInDB(**{"id_indicador": 19,
							"name":"Oportunidad en la atención de subrogaciones",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Subrogaciones gestionadas / (Subrogaciones tramitadas + subrogaciones detenidas)",
							"calculo":"79 / ( 61 + 18 )",
							"comentario":"Indicadores con corte al jueves 24 de marzo, en razón a que el cierre del sistema se realiza el viernes al finalizar la operación, por lo tanto no es posible obtener informción al corte del viernes",
							"ponderado":99.6,
							"lgreen":98,
							"lyellow":"N/A",
							"lred":98}),
	"Indicador20": IndicadorInDB(**{"id_indicador": 20,
							"name":"Partidas pendientes de pagos por aplicar con fecha efectiva",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Ajustes realizados * 1 / Ajustes pendientes",
							"calculo":"1*1 / 0",
							"comentario":"Indicadores con corte al jueves 24 de marzo, en razón a que el cierre del sistema se realiza el viernes al finalizar la operación, por lo tanto no es posible obtener informción al corte del viernes",
							"ponderado":97.6,
							"lgreen":98,
							"lyellow":"97",
							"lred":97}),
	"Indicador21": IndicadorInDB(**{"id_indicador": 21,
							"name":"Trámite de ajustes valor de intereses",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Operativa Constructor",
							"colorin":"3. Green",
							"formula":"Ajustes realizados * 1 / Ajustes pendientes",
							"calculo":"5*1 / 0",
							"comentario":"Indicadores con corte al jueves 24 de marzo, en razón a que el cierre del sistema se realiza el viernes al finalizar la operación, por lo tanto no es posible obtener informción al corte del viernes",
							"ponderado":59.2,
							"lgreen":98,
							"lyellow":"95",
							"lred":95}),
	"Indicador22": IndicadorInDB(**{"id_indicador": 22,
							"name":"Oportunidad en el giro diario del recaudo,las interfaces del recaudo y envío y recepción de cuentas",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Cartera Administradas",
							"colorin":"3. Green",
							"formula":"Promedio (Días con incumplimiento/días hábilies del mes), (Cuentas de cobro pagadas oportunamente por TC  /  Ttal cuentas de cobro generadas por BCS a la TC)",
							"calculo":"1*Promedio (4/4), (2/2)",
							"comentario":"Una parte del indicador tiene componente mensual la cual se mantiene con la información de la semana anterior",
							"ponderado":100.0,
							"lgreen":95,
							"lyellow":"80",
							"lred":80}),
	"Indicador23": IndicadorInDB(**{"id_indicador": 23,
							"name":"Cumplimiento en la atención de solicitudes de Recursos a Bancoldex",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Cartera Administradas",
							"colorin":"3. Green",
							"formula":"Días con incumplimiento / días hábilies del mes en que se solicitaron recursos",
							"calculo":"1*(4/4)",
							"comentario":"Sin informacion",
							"ponderado":100.0,
							"lgreen":100,
							"lyellow":"90",
							"lred":90}),
	"Indicador24": IndicadorInDB(**{"id_indicador": 24,
							"name":"Cumplimiento en el registro semanal de garantías ante el FNG y en el pago de facturas de comisiones",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Cartera Administradas",
							"colorin":"3. Green",
							"formula":"No de eventos confirmados oportunamente  /  No de eventos presentados en el mes",
							"calculo":"1*Promedio(2/2),(1/1)",
							"comentario":"Sin informacion",
							"ponderado":100.0,
							"lgreen":100,
							"lyellow":"90",
							"lred":90}),
	"Indicador4": IndicadorInDB(**{"id_indicador": 4,
							"name":"Efectividad en cargue y creación de operaciones compradas",
							"porcentaje":99.9,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Cartera Administradas",
							"colorin":"3. Green",
							"formula":"No de obligaciones compradas y cargadas oportunamente  /  No total de obligaciones compradas",
							"calculo":"1*(1179/1180)",
							"comentario":"Quedó pendiente la creación de una obligación de la compra a Referencia del 24 de marzo",
							"ponderado":100.0,
							"lgreen":95,
							"lyellow":"90",
							"lred":90}),
	"Indicador5": IndicadorInDB(**{"id_indicador": 5,
							"name":"Monitoreo al portafolio disponible para ATL",
							"porcentaje":99.9,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Cartera Administradas",
							"colorin":"3. Green",
							"formula":"1- el porcentaje de variación del día de la semana que mas variación se haya presentado",
							"calculo":"1%-0.01%",
							"comentario":"Sin informacion",
							"ponderado":100.0,
							"lgreen":99.5,
							"lyellow":"99.3",
							"lred":99.3}),
	"Indicador25": IndicadorInDB(**{"id_indicador": 25,
							"name":"Oportunidad en el traslado de recaudos a la PIC",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Cartera Administradas",
							"colorin":"3. Green",
							"formula":"Días con incumplimiento en el traslado del recaudo/días con recaudo en el mes",
							"calculo":"1*(7/7)",
							"comentario":"Sin informacion",
							"ponderado":100.0,
							"lgreen":95,
							"lyellow":"90",
							"lred":90}),
	"Indicador26": IndicadorInDB(**{"id_indicador": 26,
							"name":"Oportunidad en la transmisión de reportes de registro y cuentas de cobro de la cartera FRECH al Banc",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Cartera Administradas",
							"colorin":"3. Green",
							"formula":"Un registro o cuenta de cobro que no se transmita oportunamente o con inconsistencia 95% Dos registros o cuentas de cobro que no se transmitan oportunamente o con inconsistencia 90% Tres registros o cuenta de cobro que no se transmita oportunamente o",
							"calculo":"0 registros inoportunos =100%",
							"comentario":"Indicador mensual se mantierne la información de la semana anterior",
							"ponderado":100.0,
							"lgreen":100,
							"lyellow":"90",
							"lred":90}),
	"Indicador6": IndicadorInDB(**{"id_indicador": 6,
							"name":"Atención oportuna y completa de requerimientos por Custodios",
							"porcentaje":99,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Central de Garantías",
							"colorin":"3. Green",
							"formula":"total garantías recibidas,correctas y atendidas a tiempo / total garantias entregadas y solicitadas",
							"calculo":"Sin informacion",
							"comentario":"El Indicador mensual  con corte Enero  (pendiente de conciliar con Proveedores de Custodia ) Resultado  es el promedio del año  2022",
							"ponderado":100.0,
							"lgreen":99,
							"lyellow":"98",
							"lred":98}),
	"Indicador7": IndicadorInDB(**{"id_indicador": 7,
							"name":"Oportunidad trámite de Cancelación Hipotecas",
							"porcentaje":99,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Central de Garantías",
							"colorin":"3. Green",
							"formula":"(total  casos atendidos de 1 a 6 días/ Total casos radicados)+ ( total casos con inconsistencia/ total casos radicados)/2",
							"calculo":"(129/129)+(0/129) Notaria  62  (107/107)+(1/107) Notaria  51",
							"comentario":"Los valores corresponden  a la semana del 14 al 18 de  marzo. El Indicador mensual  con corte Febrero (pendiente de conciliar con notarías) Resultado  es el  promedio del año 2022",
							"ponderado":99.5,
							"lgreen":99,
							"lyellow":"98",
							"lred":98}),
	"Indicador27": IndicadorInDB(**{"id_indicador": 27,
							"name":"Efectividad en la atenció de garantías para  alistamiento proceso jurídico",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Central de Garantías",
							"colorin":"3. Green",
							"formula":"total garantías recibidas,correctas y a tiempo / total garantias solicitadas",
							"calculo":"311*1/313",
							"comentario":"El Indicador es mensual con corte  Febrero  Resultado es el promedio del año 2022",
							"ponderado":100.0,
							"lgreen":99,
							"lyellow":"98",
							"lred":98}),
	"Indicador28": IndicadorInDB(**{"id_indicador": 28,
							"name":"Atención oportuna PQR,s",
							"porcentaje":100,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Central de Garantías",
							"colorin":"3. Green",
							"formula":"Requerimientos atendidos oportunamente * 1 / Total de requerimientos a solucionar",
							"calculo":"698*5/703",
							"comentario":"Indicador mensual transmitido por la Gerencia de calidad de Servicio  con corte Febrero Resultado es el promedio del año 2022",
							"ponderado":100.0,
							"lgreen":99,
							"lyellow":"98",
							"lred":98}),
	"Indicador10": IndicadorInDB(**{"id_indicador": 10,
							"name":"Conciliación de inventario de polizas Vida e IRT",
							"porcentaje":99,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Central de Garantías",
							"colorin":"3. Green",
							"formula":"total de polizas sin novedad/ total de polizas vigentes colmena seguros total de polizas sin novedad/ total  de polizas vigentes Liberty seguros",
							"calculo":"(588,894/594,469 ) Colmena Deudores (157,626/157,631) Liberty",
							"comentario":"Indicador  de oportunidad y calidad   a Febrero de 2022 Resultado es el promedio de lo corrido del  año",
							"ponderado":99.5,
							"lgreen":99,
							"lyellow":"98",
							"lred":98}),
	"Indicador1": IndicadorInDB(**{"id_indicador": 1,
							"name":"Partidas con antigüedad Menor ó igual a 30 días.",
							"porcentaje":38,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación de Cuadre",
							"colorin":"1. Red",
							"formula":"Total Partidas menores  o igual a 30 días / Total Partidas Pendientes",
							"calculo":"9.308 / 24.630",
							"comentario":"Informe con corte Marzo 18  de 2022,  Actualmente el area se encuentra trabajando un plan de Acción  en proceso de depuración de las partidas antiguas, producto de la implementación de estrategias para atender Emergencia Sanitaria y negociaciones de",
							"ponderado":67.9,
							"lgreen":90,
							"lyellow":"80",
							"lred":80}),
	"Indicador28": IndicadorInDB(**{"id_indicador": 28,
							"name":"Atención oportuna PQR,s",
							"porcentaje":99,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Central de Garantías",
							"colorin":"3. Green",
							"formula":"Requerimientos atendidos oportunamente * 1 / Total de requerimientos a solucionar",
							"calculo":"831*1 / 847",
							"comentario":"Indicador mensual transmitido por la Gerencia de calidad de Servicio  con corte Septiembre Resultado es el promedio de lo corrido del año",
							"ponderado":99.5,
							"lgreen":99,
							"lyellow":"98",
							"lred":98}),
	"Indicador10": IndicadorInDB(**{"id_indicador": 10,
							"name":"Conciliación de inventario de polizas Vida e IRT",
							"porcentaje":99,
							"gerencia":"Gerencia Cartera Operativa",
							"central": "Coordinación Central de Garantías",
							"colorin":"3. Green",
							"formula":"total de polizas sin novedad/ total de polizas vigentes colmena seguros total de polizas sin novedad/ total  de polizas vigentes Liberty seguros",
							"calculo":"(575.730/576.333) Colmena Deudores (155.879/155.955) Liberty",
							"comentario":"Indicador  de oportunidad y calidad  conciliado a Agosto/21 Resultado es el promedio de lo corrido del  año",
							"ponderado":99.5,
							"lgreen":99,
							"lyellow":"98",
							"lred":98}),
}

def get_indicador(indicador: str):
    if indicador in database_indicadores.keys():
        return database_indicadores[indicador]
    else:
        return None
