from typing import Dict
from pydantic import BaseModel
from pydantic.errors import ArbitraryTypeError

class IndicadorInDB(BaseModel):
	id_indicador: int = 0
	name: str
	porcentaje: float
	gerencia: str
	central: str
	colorin: str
	formula: str
	calculo: str
	comentario: str
	ponderado: float
	lgreen: float
	lyellow: str
	lred: float

database_indicadores = Dict[str, IndicadorInDB]
database_indicadores = {
	"Indicador2": IndicadorInDB(**{"id_indicador": 2,
							"name":"Cajeros: Up time cajeros NCR",
							"porcentaje":96.8,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"1. Red",
							"formula":"Up time cajeros NCR",
							"calculo":"Cantidad de cajeros: 454",
							"comentario":"up time semanal del 23 al 29 de junio - la caida en comunicaciones en ATM´S de junio 29 durante 4 horas afectó el indicador semanal - se reportó al área de comunicaciones del BCS",
							"ponderado":97.1,
							"lgreen":97,
							"lyellow":"N/A",
							"lred":97}),
	"Indicador3": IndicadorInDB(**{"id_indicador": 3,
							"name":"Cajeros: Up time cajeros DIEBOLD",
							"porcentaje":96.2,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"1. Red",
							"formula":"Up time cajeros DIEBOLD",
							"calculo":"Cantidad de cajeros: 170",
							"comentario":"up time semanal del 23 al 29 de junio - la caida en comunicaciones en ATM´S de junio 29 durante 4 horas afectó el indicador semanal - se reportó al área de comunicaciones del BCS",
							"ponderado":96.7,
							"lgreen":97,
							"lyellow":"N/A",
							"lred":97}),
	"Indicador6": IndicadorInDB(**{"id_indicador": 6,
							"name":"Cajeros: Up time Multifuncionales DIEBOLD",
							"porcentaje":95.7,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"3. Green",
							"formula":"Up time Multifuncionales DIEBOLD",
							"calculo":"Cantidad de MF: 55",
							"comentario":"up time semanal del 23 al 29 de junio",
							"ponderado":94.1,
							"lgreen":95,
							"lyellow":"N/A",
							"lred":95}),
	"Indicador16": IndicadorInDB(**{"id_indicador": 16,
							"name":"Efectivo: Cumplimiento Saldo de Caja",
							"porcentaje":111.8,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"3. Green",
							"formula":"Total meta  / Total promedio semana (meta  para el 2021:  $708,000,000,000 promd)",
							"calculo":"Saldo promedio: $633.141.146.580",
							"comentario":"Semana 23 al 29 junio 2022  Promedio semanal de $708.000.000.000, autorizado por temporada pago de primas",
							"ponderado":98.4,
							"lgreen":100,
							"lyellow":"97",
							"lred":97}),
	"Indicador10": IndicadorInDB(**{"id_indicador": 10,
							"name":"Transferencias Electrónicas: Calidad lotes  aplicados",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"3. Green",
							"formula":"Lotes aplicados / Lotes recibidos",
							"calculo":"Lotes aplicados: 44.857                            Valor Total $768.567.346.578.49",
							"comentario":"Semana del 24 al 30 de junio",
							"ponderado":99.7,
							"lgreen":100,
							"lyellow":"90",
							"lred":90}),
	"Indicador11": IndicadorInDB(**{"id_indicador": 11,
							"name":"Canje: Oportunidad compensación todas las Centrales.",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"3. Green",
							"formula":"Centrales de Canje con compensación canje / transmisión a Banco de la República oportunamente",
							"calculo":"Centrales de Canje: 38. 8 Cedec, 17 CUD o delegadas teercerizadas y 13 propias delegadas. Valor Canje Rec.: $97.435.816.758.30 Valor Canje Env.: $87.811.909.597.28",
							"comentario":"Semana del 23 al 29 junio",
							"ponderado":100.0,
							"lgreen":100,
							"lyellow":"N/A",
							"lred":100}),
	"Indicador7": IndicadorInDB(**{"id_indicador": 7,
							"name":"CCB: DISPONIBILIDAD Transaccioalidad corresponsales bancarios modelo propio",
							"porcentaje":96.3,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Atención Requerimientos de Entes Extern",
							"colorin":"3. Green",
							"formula":"1 - (Número de transacciones Rechazadas / Número de transacciones Exitosas)",
							"calculo":"=1-(10539/291584)",
							"comentario":"Se detalla los rechazos operacionales de transaccionalidad en el canal, donde las de mayor volumen o relevancia no son atribuibles a fallas del canal: 265 - 5,02%  FACTURA NO EXISTE 184 - 3,48%  CUENTA ES CUENTA RECAUDADORA 155 - 2,93%  LA FECHA LIMI",
							"ponderado":96.7,
							"lgreen":95,
							"lyellow":"92",
							"lred":92}),
	"Indicador12": IndicadorInDB(**{"id_indicador": 12,
							"name":"CCB: DISPONIBILIDAD Disponibilidad tráfico de comunicación",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Soporte a Aplicaciones",
							"colorin":"3. Green",
							"formula":"Comunicación",
							"calculo":"Comunicaciòn",
							"comentario":"Durante la semana movistar no reporta fallo en la comunicación.  Indicador proporcionado por Movistar Empresas, tipo de indicador es por enlace de nivel one, que emite comunicación al rauter. Cuentan con dos reguladores en caso de falla en un rauter",
							"ponderado":82.7,
							"lgreen":99.6,
							"lyellow":"76",
							"lred":76}),
	"Indicador9": IndicadorInDB(**{"id_indicador": 9,
							"name":"CCB: DISPONIBILIDAD Oportunidad en la disponibilidad del Canal Carvajal",
							"porcentaje":98,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Coordinación Moneda Extranjera",
							"colorin":"3. Green",
							"formula":"La información es generada por el monitoreo realizado en el mes sobre la VPN, la plataforma transaccional, ventanas programadas y incidencias presentadas.",
							"calculo":"Sin informacion",
							"comentario":"Sin informacion",
							"ponderado":91.0,
							"lgreen":98,
							"lyellow":"90",
							"lred":90}),
	"Indicador13": IndicadorInDB(**{"id_indicador": 13,
							"name":"Convenios: Oportunidad en la inclusión de negociaciones vinculación o mantenimiento Clientes Empresa",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Cuadre",
							"colorin":"3. Green",
							"formula":"Solicitudes atendidas oportunamente (Fuente Herramienta de negociación Star Cash estado de la propuesta) / Total solicitudes recibidas (Fuente excel herremienta de gestión y Control Cash relación diaria)",
							"calculo":"175  CLIENTES  - 319 PRODUCTOS HABILITADOS",
							"comentario":"UP TIME SEMANAL DEL 24 AL 30 DE JUNIO 2022",
							"ponderado":99.4,
							"lgreen":100,
							"lyellow":"90",
							"lred":90}),
	"Indicador5": IndicadorInDB(**{"id_indicador": 5,
							"name":"Oportunidad en la atención de Embargos-Desembargos",
							"porcentaje":93,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Cuadre",
							"colorin":"2. Yellow",
							"formula":"Embargos-Desembargos atendidos oportunamente /  Total Embargos-Desembargos radicados *Fuente: Sistema de embargos",
							"calculo":"Identificaciones Capturadas 19.119 Identificaciones Oportunas (1-3 dias) 17.741 Identificaciones Inoportunas (4 ó mas dias ) 1.362 Identificaciones Pendientes  16",
							"comentario":"Semana del 20 al 26 de junio de 2022 Indicador afectado por error en sistema de embargos que no permtía captura de oficios",
							"ponderado":99.0,
							"lgreen":96,
							"lyellow":"90",
							"lred":90}),
	"Indicador1": IndicadorInDB(**{"id_indicador": 1,
							"name":"CSCB: Atención casos escalados por OMAT por correo (En construcción y validación con otras áreas)",
							"porcentaje":95.6,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Operaciones Convenios Empresariales",
							"colorin":"1. Red",
							"formula":"# de casos atendidos / # casos asignados en Service Now Fuente: Notificaciones enviadas por Service Now  y registro de los casos atendidos en el grupo..",
							"calculo":"Identificaciones Oportunas (1-3 dias) 17.741",
							"comentario":"Semana del 24 al 30 de junio de 2022",
							"ponderado":99.7,
							"lgreen":100,
							"lyellow":"97.9",
							"lred":97.9}),
	"Indicador4": IndicadorInDB(**{"id_indicador": 4,
							"name":"COI: Cumplimiento de operaciones Clientes",
							"porcentaje":92.4,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Centro Operación Empresarial  - Fiduciario",
							"colorin":"2. Yellow",
							"formula":"Operaciones para tramitar en el exterior/ Operaciones enviadas por oficinas.",
							"calculo":"Identificaciones Inoportunas (4 ó mas dias ) 1.362",
							"comentario":"Semana del 24 al 30 de junio de 2022",
							"ponderado":97.6,
							"lgreen":100,
							"lyellow":"90",
							"lred":90}),
	"Indicador14": IndicadorInDB(**{"id_indicador": 14,
							"name":"CC: Oportunidad en conciliación",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Soporte operativo Corresponsales Bancarios",
							"colorin":"3. Green",
							"formula":"Canales  a conciliar (oficinas, centros de canje, cajeros corresponsales propios, Carvajal, Efectivo clientes,centros de efectivo,AFC,impuestos, ACH, transferencias ya, mi pago amigo ) / canales  conciliados",
							"calculo":"Identificaciones Pendientes  16",
							"comentario":"semana del 24 al 30 junio/22",
							"ponderado":100.4,
							"lgreen":100,
							"lyellow":"93",
							"lred":93}),
	"Indicador8": IndicadorInDB(**{"id_indicador": 8,
							"name":"COE: Oportunidad transacciones atendidas en los tiempos definidos ANS",
							"porcentaje":97.1,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Soporte operativo Corresponsales Bancarios",
							"colorin":"3. Green",
							"formula":"Transacciones cumplidas según ANS / solicitudes radicadas [Fuente: Excel - Inventario de solicitudes]",
							"calculo":"Semanal    Q 1,318      $ 340,168 MMll",
							"comentario":"semana del 24 al 30 junio/22",
							"ponderado":98.2,
							"lgreen":95,
							"lyellow":"97",
							"lred":97}),
	"Indicador15": IndicadorInDB(**{"id_indicador": 15,
							"name":"Número total operaciones cumplidas/ operaciones a cumplir.",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "UAC Back Office",
							"colorin":"3. Green",
							"formula":"Número total operaciones cumplidas/ operaciones a cumplir.",
							"calculo":"Se atendieron 599 operaciones por u valor total de $4.499.069.917259.02",
							"comentario":"Semana del 24 al 30 de junio de 2022",
							"ponderado":100.0,
							"lgreen":100,
							"lyellow":"N/A",
							"lred":100}),
}

def get_indicador(indicador: str):
    if indicador in database_indicadores.keys():
        return database_indicadores[indicador]
    else:
        return None
