from typing import Dict
from pydantic import BaseModel
from pydantic.errors import ArbitraryTypeError

class IndicadorInDB(BaseModel):
	id_indicador: int = 0
	name: str
	porcentaje: float
	gerencia: str
	central: str
	colorin: str
	formula: str
	calculo: str
	comentario: str
	ponderado: float
	lgreen: float
	lyellow: str
	lred: float

database_indicadores = Dict[str, IndicadorInDB]
database_indicadores = {
	"Indicador8": IndicadorInDB(**{"id_indicador": 8,
							"name":"Cajeros: Up time cajeros NCR",
							"porcentaje":97.8,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"3. Green",
							"formula":"Up time cajeros NCR",
							"calculo":"Cantidad de cajeros: 453",
							"comentario":"up time semanal del 12 al 18 de mayo",
							"ponderado":97.2,
							"lgreen":97,
							"lyellow":"N/A",
							"lred":97}),
	"Indicador5": IndicadorInDB(**{"id_indicador": 5,
							"name":"Cajeros: Up time cajeros DIEBOLD",
							"porcentaje":96.7,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"1. Red",
							"formula":"Up time cajeros DIEBOLD",
							"calculo":"Cantidad de cajeros: 171",
							"comentario":"up time semanal del 12 al 18 de mayo - la capacidad de respuesta oportuna en servicios de DIEBOLD disminuyó - Se realiza reunión de seguimiento con el proveedor",
							"ponderado":96.7,
							"lgreen":97,
							"lyellow":"N/A",
							"lred":97}),
	"Indicador4": IndicadorInDB(**{"id_indicador": 4,
							"name":"Cajeros: Up time Multifuncionales DIEBOLD",
							"porcentaje":94.8,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"1. Red",
							"formula":"Up time Multifuncionales DIEBOLD",
							"calculo":"Cantidad de MF: 55",
							"comentario":"up time semanal del 12 al 18 de mayo - la capacidad de respuesta oportuna en servicios de DIEBOLD disminuyó - Se realiza reunión de seguimiento con el proveedor",
							"ponderado":94.2,
							"lgreen":95,
							"lyellow":"N/A",
							"lred":95}),
	"Indicador3": IndicadorInDB(**{"id_indicador": 3,
							"name":"Efectivo: Cumplimiento Saldo de Caja",
							"porcentaje":91.6,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"1. Red",
							"formula":"Total meta  / Total promedio semana (meta  para el 2021:  $590,000,000,000 promd)",
							"calculo":"Saldo promedio: $643.819.399.950",
							"comentario":"Semana 12 al 18 Mayo 2022 - Incremento de los saldos de caja por ingreso de efectivo baja denominación, restringido para consignar al Banco de la República.  - Migración billete de 100.000 ATMs",
							"ponderado":96.6,
							"lgreen":100,
							"lyellow":"97",
							"lred":97}),
	"Indicador11": IndicadorInDB(**{"id_indicador": 11,
							"name":"Transferencias Electrónicas. Calidad lotes  aplicados",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"3. Green",
							"formula":"Lotes aplicados / Lotes recibidos",
							"calculo":"Lotes aplicados: 39.033                                                                               Valor Total $483.743.462.262.18",
							"comentario":"Semana del 13 al 19 de mayo",
							"ponderado":99.6,
							"lgreen":100,
							"lyellow":"97",
							"lred":97}),
	"Indicador12": IndicadorInDB(**{"id_indicador": 12,
							"name":"Canje: Oportunidad compensación todas las Centrales.",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"3. Green",
							"formula":"Centrales de Canje con compensación canje / transmisión a Banco de la República oportunamente",
							"calculo":"Centrales de Canje: 38. 8 Cedec, 17 CUD o delegadas teercerizadas y 13 propias delegadas. Valor Canje Rec.: $139.716.196.311.14 Valor Canje Env.: $140.696.676.101.20",
							"comentario":"Semana del 12 al 18 mayo",
							"ponderado":100.0,
							"lgreen":100,
							"lyellow":"N/A",
							"lred":100}),
	"Indicador7": IndicadorInDB(**{"id_indicador": 7,
							"name":"Oportunidad en la atención de Embargos-Desembargos",
							"porcentaje":96.9,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Atención Requerimientos de Entes Extern",
							"colorin":"3. Green",
							"formula":"Embargos-Desembargos atendidos oportunamente /  Total Embargos-Desembargos radicados *Fuente: Sistema de embargos",
							"calculo":"=1-(9817/321677)",
							"comentario":"Los rechazos con mayor relevancia pero que no son afectacion por el canal 13 y 19 de mayo: 2.686 - 39,70%  W2- FONDOS INSUFICIENTES PARA RETIRO 614 - 9,07%  FACTURA NO EXISTE 531 - 7,85%  ERROR INESPERADO EN LA CONSULTA 360 - 5,32%  CUENTA ES CUENTA",
							"ponderado":96.0,
							"lgreen":95,
							"lyellow":"92",
							"lred":92}),
	"Indicador13": IndicadorInDB(**{"id_indicador": 13,
							"name":"CSCB: Atención casos escalados por OMAT por correo (En construcción y validación con otras áreas)",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Soporte a Aplicaciones",
							"colorin":"3. Green",
							"formula":"# de casos atendidos / # casos asignados en Service Now Fuente: Notificaciones enviadas por Service Now  y registro de los casos atendidos en el grupo..",
							"calculo":"Comunicaciòn",
							"comentario":"Durante la semana movistar no reporta fallo en la comunicación. Indicador proporcionado por Movistar Empresas, tipo de indicador es por enlace de nivel one, que emite comunicación al rauter. Cuentan con dos reguladores en caso de falla en un rauter p",
							"ponderado":86.0,
							"lgreen":99.6,
							"lyellow":"76",
							"lred":76}),
	"Indicador1": IndicadorInDB(**{"id_indicador": 1,
							"name":"COI: Cumplimiento de operaciones Clientes",
							"porcentaje":85.7,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Coordinación Moneda Extranjera",
							"colorin":"1. Red",
							"formula":"Operaciones para tramitar en el exterior/ Operaciones enviadas por oficinas.",
							"calculo":"La información es generada por el monitoreo realizado en el mes sobre la VPN, la plataforma transaccional, ventanas programadas y incidencias presentadas.",
							"comentario":"Información suministrada por el aliado Carvajal a corte quincenal mayo 2022, Novedad en comunicación del 8 y 9 de mayo falla en Carvajal. La información es generada por assenda red, el monitoreo realizado en el mes sobre la VPN, la plataforma transac",
							"ponderado":91.3,
							"lgreen":98,
							"lyellow":"90",
							"lred":90}),
	"Indicador14": IndicadorInDB(**{"id_indicador": 14,
							"name":"CC: Oportunidad en conciliación",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Cuadre",
							"colorin":"3. Green",
							"formula":"Canales  a conciliar (oficinas, centros de canje, cajeros corresponsales propios, Carvajal, Efectivo clientes,centros de efectivo,AFC,impuestos, ACH, transferencias ya, mi pago amigo ) / canales  conciliados",
							"calculo":"169 Clientes  372 Productos",
							"comentario":"Semana del 13 al 19 de mayo",
							"ponderado":99.4,
							"lgreen":100,
							"lyellow":"90",
							"lred":90}),
	"Indicador9": IndicadorInDB(**{"id_indicador": 9,
							"name":"CC: Partidas pendientes mayores a 30 días",
							"porcentaje":97.9,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Cuadre",
							"colorin":"3. Green",
							"formula":"Partidas conciliatorias mayores a 30 días sin ajustar resultado de la conciliación contable  mensual con corte al mes anterior / total partidas conciliatorias presentadas durante el  mes",
							"calculo":"Identificaciones Capturadas 26.398 Identificaciones Oportunas (1-3 dias) 25.851 Identificaciones Inoportunas (4 ó mas dias ) 522 Identificaciones Pendientes  25",
							"comentario":"Semana del 2 al 8 de mayo",
							"ponderado":99.2,
							"lgreen":96,
							"lyellow":"90",
							"lred":90}),
	"Indicador2": IndicadorInDB(**{"id_indicador": 2,
							"name":"CCE: Oportunidad en la inclusión de negociaciones vinculación o mantenimiento Clientes Empresariales",
							"porcentaje":88.3,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Operaciones Convenios Empresariales",
							"colorin":"1. Red",
							"formula":"Solicitudes atendidas oportunamente (Fuente Herramienta de negociación Star Cash estado de la propuesta) / Total solicitudes recibidas (Fuente excel herremienta de gestión y Control Cash relación diaria)",
							"calculo":"257 (# casos asignados en Service Now)",
							"comentario":"Semana del 13 al 19 de mayo",
							"ponderado":98.9,
							"lgreen":100,
							"lyellow":"97",
							"lred":97}),
	"Indicador6": IndicadorInDB(**{"id_indicador": 6,
							"name":"COE: Oportunidad transacciones atendidas en los tiempos definidos ANS",
							"porcentaje":91.9,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Centro Operación Empresarial  - Fiduciario",
							"colorin":"2. Yellow",
							"formula":"Transacciones cumplidas según ANS / solicitudes radicadas [Fuente: Excel - Inventario de solicitudes]",
							"calculo":"Op. Recibidas de clientes 334 Op. Cumplidas 307 por valor de USD 3,587.419,91",
							"comentario":"Semana del 13 al 19 de mayo",
							"ponderado":97.4,
							"lgreen":100,
							"lyellow":"90",
							"lred":90}),
	"Indicador15": IndicadorInDB(**{"id_indicador": 15,
							"name":"CCB: Oportunidad en la disponibilidad del Canal Modelo Propio",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Soporte operativo Corresponsales Bancarios",
							"colorin":"3. Green",
							"formula":"1 - (Número de transacciones Rechazadas / Número de transacciones Exitosas)",
							"calculo":"6,619 puntos conciliados 5,654 Ajustes aplicados",
							"comentario":"Semana del 13 al 19 de mayo",
							"ponderado":100.7,
							"lgreen":100,
							"lyellow":"93",
							"lred":93}),
	"Indicador10": IndicadorInDB(**{"id_indicador": 10,
							"name":"CCB: Oportunidad en la disponibilidad del Canal Carvajal",
							"porcentaje":99.4,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Soporte operativo Corresponsales Bancarios",
							"colorin":"3. Green",
							"formula":"La información es generada por el monitoreo realizado en el mes sobre la VPN, la plataforma transaccional, ventanas programadas y incidencias presentadas.",
							"calculo":"Semanal  Q 1,146     -   $ 271,748 MMll",
							"comentario":"Semana del 13 al 19 de mayo",
							"ponderado":98.3,
							"lgreen":90,
							"lyellow":"98",
							"lred":98}),
	"Indicador16": IndicadorInDB(**{"id_indicador": 16,
							"name":"BO: Oportunidad en el cumplimiento de operaciones del Piso Financiero y otras Áreas de las empresas",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "UAC Back Office",
							"colorin":"3. Green",
							"formula":"Número total operaciones cumplidas/ operaciones a cumplir.",
							"calculo":"Se atendieron 575 operaciones por valor de $3.282.098.671.033.36",
							"comentario":"Semana del 13 al 19 de mayo",
							"ponderado":100.0,
							"lgreen":100,
							"lyellow":"N/A",
							"lred":100}),
}

def get_indicador(indicador: str):
    if indicador in database_indicadores.keys():
        return database_indicadores[indicador]
    else:
        return None
